Fix SG rule creation on new VPC
When attempting to create SG rules for SGs that haven't yet been created,
i.e. `interface_vpce_source_security_group_ids = [aws_security_group.my_sg.id]`
and `my_sg` isn't present, Terraform complains like this:

```
Error: Invalid for_each argument
  on .terraform/modules/vpc/terraform-aws-vpc-3.0.1/vpc_endpoints.tf line 63, in resource "aws_security_group_rule" "vpce_source_https_ingress":
  63:   for_each = var.interface_vpce_source_security_group_ids
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

Fix that by simply using a count; there's no need for the complex loop logic
that `for_each` provides.